In [7]:
import torch
import torch.nn as nn
from torchvision.models import convnext_base

In [73]:
model = convnext_base(num_classes=10000)
print(model)

ConvNeXt(
  (features): Sequential(
    (0): Conv2dNormActivation(
      (0): Conv2d(3, 128, kernel_size=(4, 4), stride=(4, 4))
      (1): LayerNorm2d((128,), eps=1e-06, elementwise_affine=True)
    )
    (1): Sequential(
      (0): CNBlock(
        (block): Sequential(
          (0): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3), groups=128)
          (1): Permute()
          (2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
          (3): Linear(in_features=128, out_features=512, bias=True)
          (4): GELU(approximate='none')
          (5): Linear(in_features=512, out_features=128, bias=True)
          (6): Permute()
        )
        (stochastic_depth): StochasticDepth(p=0.0, mode=row)
      )
      (1): CNBlock(
        (block): Sequential(
          (0): Conv2d(128, 128, kernel_size=(7, 7), stride=(1, 1), padding=(3, 3), groups=128)
          (1): Permute()
          (2): LayerNorm((128,), eps=1e-06, elementwise_affine=True)
          (3): Linear(

In [75]:
model.avgpool = nn.Identity()
model.classifier = nn.Identity()

In [77]:
model(torch.zeros((1,3,244,244))).shape

torch.Size([1, 1024, 7, 7])

In [142]:
test = torch.full((2, 5), 0.1)
test[0][1] = 1
test[1][2] = 1
t = test.view(2, 5, 1, 1).repeat(1, 1, 7, 7)#.permute([0, 3, 1, 2])
print(t.shape)
print(t[1][2])

torch.Size([2, 5, 7, 7])
tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])


In [50]:
fc = nn.Linear(3,3)

In [51]:
pm = torch.permute(torch.eye(5).repeat((3, 1, 1)).unsqueeze(0), [0, 2, 3, 1]).type(torch.float32)
ln = nn.LayerNorm((3,), eps=1e-06)

print(pm.shape)
pm = ln(pm)
pm = fc(pm)
print(pm.shape)
torch.permute(pm, [0, 3, 1, 2])

torch.Size([1, 5, 5, 3])
torch.Size([1, 5, 5, 3])


tensor([[[[-0.2255, -0.2255, -0.2255, -0.2255, -0.2255],
          [-0.2255, -0.2255, -0.2255, -0.2255, -0.2255],
          [-0.2255, -0.2255, -0.2255, -0.2255, -0.2255],
          [-0.2255, -0.2255, -0.2255, -0.2255, -0.2255],
          [-0.2255, -0.2255, -0.2255, -0.2255, -0.2255]],

         [[-0.5156, -0.5156, -0.5156, -0.5156, -0.5156],
          [-0.5156, -0.5156, -0.5156, -0.5156, -0.5156],
          [-0.5156, -0.5156, -0.5156, -0.5156, -0.5156],
          [-0.5156, -0.5156, -0.5156, -0.5156, -0.5156],
          [-0.5156, -0.5156, -0.5156, -0.5156, -0.5156]],

         [[ 0.0451,  0.0451,  0.0451,  0.0451,  0.0451],
          [ 0.0451,  0.0451,  0.0451,  0.0451,  0.0451],
          [ 0.0451,  0.0451,  0.0451,  0.0451,  0.0451],
          [ 0.0451,  0.0451,  0.0451,  0.0451,  0.0451],
          [ 0.0451,  0.0451,  0.0451,  0.0451,  0.0451]]]],
       grad_fn=<PermuteBackward0>)

In [43]:
torch.eye(5).repeat((3, 1, 1)).unsqueeze(0).shape

torch.Size([1, 3, 5, 5])

In [55]:
pm = torch.eye(5).repeat((3, 1, 1)).unsqueeze(0)
fc(pm)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (15x5 and 3x3)

In [152]:
t = torch.tensor([10000, 0, 3], dtype=torch.float32)
mean, std, var = torch.mean(t), torch.std(t), torch.var(t)
t  = (t-mean)/std
t

tensor([ 1.1547, -0.5776, -0.5771])